# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48863a534f4a9c0511b4497fda645f1fc097840e8d8b0ef018ca0b473857b30d23ad38cdcd4ab2b660f0219343890631647ec17554243fea619e5baa2e70f0af

test:
  secret_key_base: cec90bb7fbac39fb41541afc90fb4ece1e7cafad3aced99c16cd8e5d17738beface9b47bd785d280f6a861f2bf82bd6e1af66bf33329e3f0512dcd435002d4c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
